/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadeunidade6questao2;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSelecione = new javax.swing.JLabel();
        jlPolo = new javax.swing.JLabel();
        jlSelecionado = new javax.swing.JLabel();
        jtAdicionarPolo = new javax.swing.JTextField();
        jbAdicione = new javax.swing.JButton();
        jbRemova = new javax.swing.JButton();
        jcbOpcoes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlSelecione.setText("Selecione o seu Polo EAD Univates:");

        jlPolo.setText("Polo");

        jlSelecionado.setText("selecionado");

        jtAdicionarPolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAdicionarPoloActionPerformed(evt);
            }
        });

        jbAdicione.setText("Adicione");
        jbAdicione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicioneActionPerformed(evt);
            }
        });

        jbRemova.setText("Remova");
        jbRemova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemovaActionPerformed(evt);
            }
        });

        jcbOpcoes.setEditable(true);
        jcbOpcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>", "Alvorada", "Arroio do Meio", "Arvorezinha", "Bom Retiro do Sul", "Carlos Barbosa", "Cruz Alta", "Encantado", "Estrela", "Garibaldi", "Guaporé", "Lajeado", "Ibirubá", "Porto Alegre", "Serafina Corrêa", "Soledade", "Taquari", "Teutônia", "Venâncio Aires", "Veranópolis" }));
        jcbOpcoes.setAutoscrolls(true);
        jcbOpcoes.setOpaque(false);
        jcbOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSelecione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPolo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtAdicionarPolo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdicione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemova))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPolo)
                    .addComponent(jlSelecionado)
                    .addComponent(jtAdicionarPolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicione)
                    .addComponent(jbRemova)
                    .addComponent(jlSelecione)
                    .addComponent(jcbOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAdicionarPoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAdicionarPoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAdicionarPoloActionPerformed

    private void jcbOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcoesActionPerformed
                        
        if ( jcbOpcoes.getSelectedItem().equals("<Selecione uma das opções>"))
        {
            JOptionPane.showMessageDialog(null, "Opção errada");
        }
        else {
            String verificaPolo = String.valueOf( jcbOpcoes.getSelectedItem() );
            jlPolo.setText( verificaPolo );
        } 
              
    }//GEN-LAST:event_jcbOpcoesActionPerformed

    private void jbAdicioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicioneActionPerformed
       if ( jtAdicionarPolo.getText().equals("") )
        {
            JOptionPane.showMessageDialog( null, "Sem polo a adicionar");
        }
        
        else 
        {
            String adicionaPolo = jtAdicionarPolo.getText();
        
            jcbOpcoes.addItem( adicionaPolo );
            jtAdicionarPolo.setText("");
            JOptionPane.showMessageDialog( null, "Novo Polo Adicionado: " +adicionaPolo );
        }
        
    }//GEN-LAST:event_jbAdicioneActionPerformed

    private void jbRemovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemovaActionPerformed
        
        String verificaPolo = String.valueOf( jcbOpcoes.getSelectedItem() );
        
        if ( jcbOpcoes.getSelectedItem().equals("<Selecione uma das opções>"))
        {
            JOptionPane.showMessageDialog(null, "Escolha um Polo válido para remover");
        }
        
        else
        {
            jcbOpcoes.removeItem( verificaPolo );
            JOptionPane.showMessageDialog( null, "Polo removido: " +verificaPolo );
        }
    }//GEN-LAST:event_jbRemovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        AplicaNimbusLookAndFeel.pegaNimbus();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdicione;
    private javax.swing.JButton jbRemova;
    private javax.swing.JComboBox<String> jcbOpcoes;
    private javax.swing.JLabel jlPolo;
    private javax.swing.JLabel jlSelecionado;
    private javax.swing.JLabel jlSelecione;
    private javax.swing.JTextField jtAdicionarPolo;
    // End of variables declaration//GEN-END:variables
}
